
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: src/main/resources/script/prod_log.log
  level:
    org:
      hibernate:
        SQL: INFO
      springframework:
        web: INFO
        data: INFO
      boot:
        autoconfigure:
          data:
            rest: INFO
            jpa: INFO
            orm: INFO
  logback.rollingpolicy.clean-history-on-start: false

