apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxy-client.fullname" . }}-config
  labels:
    {{- include "proxy-client.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      application:
        name: proxy-client
    server:
      port: {{ .Values.service.targetPort }}
    management:
      endpoints:
        web:
          exposure:
            include: health,info,prometheus,metrics